spring.datasource.url=jdbc:postgresql://localhost:5432/ai_knowledge_db
spring.datasource.username=postgres
spring.datasource.password=901231
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=TRACE

# ==========================
# File Upload Configuration
# ==========================

file.upload-dir=uploads

file.pdf-max-size=104857600
file.image-max-size=20971520
file.audio-max-size=209715200
file.video-max-size=524288000

# ==========================
# Multipart Upload Configuration
# ==========================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.resolve-lazily=true